sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tHHV7h6QacDrEDhimZZ
    access-key-secret: kyVCiML7EglyVNkmOyrscjEoqFYXmc
    bucket-name: sky-take-out-shumei
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wxe9e09375ad790ef3
    secret: e0aa15c21a65e9cdcf30e2a863e7465b
